# Generated by Django 2.0.7 on 2018-10-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('user_ip', models.GenericIPAddressField(default='ip')),
                ('user_agent', models.CharField(default='useragent', max_length=500)),
                ('cookies', models.TextField(default='cookies', max_length=100000)),
            ],
        ),
    ]
